services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=skinet;Username=appuser;Password=eCom123!
      ConnectionStrings__IdentityConnection: Host=db;Port=5432;Database=identity;Username=appuser;Password=eCom123!
      Token__Issuer: http://localhost:8080
      ApiUrl: http://localhost:8080/Content/
      RUN_MIGRATIONS: "false"
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: eCom123!
      POSTGRES_USER: appuser
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
